services:
  postgres:
    image: "postgres:15"
    environment:
      POSTGRES_USER: "u"
      POSTGRES_PASSWORD: "p"
      POSTGRES_DB: "db"
    ports:
      - "5432:5432"
    volumes:
      - "postgres_volume:/var/lib/postgresql/data"

volumes:
  postgres_volume:
