// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: messages.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMessage = `-- name: CreateMessage :one
INSERT INTO messages (
    id, 
    created_at,
    raw,
    source_id
) VALUES (
    DEFAULT, NOW(), $1, $2
) RETURNING id, raw, created_at, source_id
`

type CreateMessageParams struct {
	Raw      pgtype.Text
	SourceID int32
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error) {
	row := q.db.QueryRow(ctx, createMessage, arg.Raw, arg.SourceID)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.Raw,
		&i.CreatedAt,
		&i.SourceID,
	)
	return i, err
}

const getMessage = `-- name: GetMessage :one
SELECT id, raw, created_at, source_id FROM messages WHERE id = $1 LIMIT 1
`

func (q *Queries) GetMessage(ctx context.Context, id int64) (Message, error) {
	row := q.db.QueryRow(ctx, getMessage, id)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.Raw,
		&i.CreatedAt,
		&i.SourceID,
	)
	return i, err
}

const getMessagesAsc = `-- name: GetMessagesAsc :many
SELECT id, created_at, raw FROM messages ORDER BY id ASC LIMIT $1 OFFSET $2
`

type GetMessagesAscParams struct {
	Limit  int32
	Offset int32
}

type GetMessagesAscRow struct {
	ID        int64
	CreatedAt pgtype.Timestamp
	Raw       pgtype.Text
}

func (q *Queries) GetMessagesAsc(ctx context.Context, arg GetMessagesAscParams) ([]GetMessagesAscRow, error) {
	rows, err := q.db.Query(ctx, getMessagesAsc, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMessagesAscRow
	for rows.Next() {
		var i GetMessagesAscRow
		if err := rows.Scan(&i.ID, &i.CreatedAt, &i.Raw); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMessagesDesc = `-- name: GetMessagesDesc :many
SELECT id, created_at, raw FROM messages ORDER BY id DESC LIMIT $1 OFFSET $2
`

type GetMessagesDescParams struct {
	Limit  int32
	Offset int32
}

type GetMessagesDescRow struct {
	ID        int64
	CreatedAt pgtype.Timestamp
	Raw       pgtype.Text
}

func (q *Queries) GetMessagesDesc(ctx context.Context, arg GetMessagesDescParams) ([]GetMessagesDescRow, error) {
	rows, err := q.db.Query(ctx, getMessagesDesc, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMessagesDescRow
	for rows.Next() {
		var i GetMessagesDescRow
		if err := rows.Scan(&i.ID, &i.CreatedAt, &i.Raw); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMessagesWhereSourceId = `-- name: GetMessagesWhereSourceId :many
SELECT id, raw, created_at FROM messages WHERE source_id = $1 AND raw ilike $2
    ORDER BY id DESC LIMIT $3 OFFSET $4
`

type GetMessagesWhereSourceIdParams struct {
	SourceID int32
	Raw      pgtype.Text
	Limit    int32
	Offset   int32
}

type GetMessagesWhereSourceIdRow struct {
	ID        int64
	Raw       pgtype.Text
	CreatedAt pgtype.Timestamp
}

func (q *Queries) GetMessagesWhereSourceId(ctx context.Context, arg GetMessagesWhereSourceIdParams) ([]GetMessagesWhereSourceIdRow, error) {
	rows, err := q.db.Query(ctx, getMessagesWhereSourceId,
		arg.SourceID,
		arg.Raw,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMessagesWhereSourceIdRow
	for rows.Next() {
		var i GetMessagesWhereSourceIdRow
		if err := rows.Scan(&i.ID, &i.Raw, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
