// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package sqlc

import (
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

type Message struct {
	ID        int64
	Raw       pgtype.Text
	RawJsonb  []byte
	CreatedAt pgtype.Timestamp
	SourceID  int32
}

type Source struct {
	ID int32
	Ip netip.Addr
}
