// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Message struct {
	ID        int64
	Raw       pgtype.Text
	RawJsonb  []byte
	CreatedAt pgtype.Timestamp
}
