name: deploy-prod

on:
  push:
    branches:
      - master

jobs:
  deploy-prod:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: save ssh key
        run: |
          mkdir -p ~/.ssh/
          touch ~/.ssh/tgator
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/tgator
          chmod 400 ~/.ssh/tgator
      
      - name: build image
        run: docker image build --tag dokku/tgator:${{ github.sha }} .

      - name: deploy image
        run: |
          ssh-keyscan ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts
          docker image save dokku/tgator:${{ github.sha }} | ssh dokku@${{ secrets.SERVER_IP }} -i ~/.ssh/tgator git:load-image tgator dokku/tgator:${{ github.sha }}

      - name: ssh cleanup
        run: rm -rf ~/.ssh
